time: 2014-01-08 09:22:45.584001Z
tags: worker-0
test: setUpClass (tempest.scenario.test_volume_boot_pattern.TestVolumeBootPattern)
time: 2014-01-08 09:22:45.584001Z
failure: setUpClass (tempest.scenario.test_volume_boot_pattern.TestVolumeBootPattern) [ multipart
Content-Type: text/x-traceback;charset="utf8",language="python"
traceback
7BB
Traceback (most recent call last):
  File "/home/os1/tempest/tempest/scenario/test_volume_boot_pattern.py", line 49, in setUpClass
    super(TestVolumeBootPattern, cls).setUpClass()
  File "/home/os1/tempest/tempest/scenario/manager.py", line 500, in setUpClass
    super(NetworkScenarioTest, cls).setUpClass()
  File "/home/os1/tempest/tempest/scenario/manager.py", line 211, in setUpClass
    username, tenant_name, password = cls.credentials()
  File "/home/os1/tempest/tempest/scenario/manager.py", line 226, in credentials
    return cls.isolated_creds.get_primary_creds()
  File "/home/os1/tempest/tempest/common/isolated_creds.py", line 326, in get_primary_creds
    user, tenant = self._create_creds()
  File "/home/os1/tempest/tempest/common/isolated_creds.py", line 156, in _create_creds
    description=tenant_desc)
  File "/home/os1/tempest/tempest/common/isolated_creds.py", line 86, in _create_tenant
    description=description)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v2_0/tenants.py", line 90, in create
    return self._create('/tenants', params, "tenant")
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/base.py", line 146, in _create
    return self._post(url, body, response_key, return_raw)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/base.py", line 159, in _post
    resp, body = self.client.post(url, body=body)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 661, in post
    return self._cs_request(url, 'POST', **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 651, in _cs_request
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 610, in request
    **request_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 124, in request
    raise exceptions.from_response(resp, method, url)
ServiceUnavailable: Service Unavailable (HTTP 503)
0
]
tags: -worker-0
time: 2014-01-08 09:22:45.830483Z
tags: worker-0
test: process-returncode
time: 2014-01-08 09:22:45.830483Z
failure: process-returncode [ multipart
Content-Type: test/plain;charset=utf8
traceback
C
returncode 10
]
tags: -worker-0
